use std::collections::{HashMap, HashSet};

fn main() {
    println!("1 test {}", solve_1(output_test()));
    println!("1 source {}", solve_1(output_source()));
    println!("2 test {}", solve_2(input_test(), output_test()));
    println!("2 test {}", solve_2(input_source(), output_source()));
}

#[derive(Eq, Hash, PartialEq, Clone)]
enum Segment {
    Top,
    Bottom,
    Middle,
    LeftTop,
    LeftBottom,
    RightTop,
    RightBottom
}

fn solve_1(output: Vec<Vec<String>>) -> i32 {
    output.iter().flatten().filter(|s| s.len() == 2 || s.len() == 3 || s.len() == 4 || s.len() == 7 ).count() as i32
}

fn solve_2(input: Vec<Vec<String>>, output: Vec<Vec<String>>) -> i64 {
    let mut res: i64 = 0;
    for i in 0..input.len() {
        // 1. Find 1 and 7 and figure out the top segment
        let mut sectors: HashMap<char, Segment> = HashMap::new();
        let seven = input[i].iter().filter(|s| s.len() == 3).nth(0).unwrap();
        let one = input[i].iter().filter(|s| s.len() == 2).nth(0).unwrap();
        let top = seven.chars().filter(|c| !(*one).contains(&c.to_string())).nth(0).unwrap();
        sectors.insert(top, Segment::Top);
        // 2. Find out ltop, lbot and rbot by counting the occasions -- 5, 4 and 9 respectively
        let occasions: HashMap<char, i32> = input[i].iter().map(|s| s.chars()).flatten().fold(HashMap::new(), |mut acc, next| {
            if let Some(num) = acc.get_mut(&next) {
                *num += 1;
            } else {
                acc.insert(next, 1);
            };
            acc
        });
        let (ltop, _) = occasions.iter().filter(|(_,v)| **v == 6).nth(0).unwrap();
        let (lbot, _) = occasions.iter().filter(|(_,v)| **v == 4).nth(0).unwrap();
        let (rbot, _) = occasions.iter().filter(|(_,v)| **v == 9).nth(0).unwrap();
        sectors.insert(*ltop, Segment::LeftTop);
        sectors.insert(*lbot, Segment::LeftBottom);
        sectors.insert(*rbot, Segment::RightBottom);
        // 2.1. Find out rtop -- it is equal to 8 as well as top, but we already know the top char
        let (rtop, _) = occasions.iter().filter(|(k, v)| **v == 8 && **k != top).nth(0).unwrap();
        sectors.insert(*rtop, Segment::RightTop);
        // 3. Find out mid -- take 1 and 4, remove matching and ltop
        let four = input[i].iter().filter(|s| s.len() == 4).nth(0).unwrap();
        let mid = four.chars().filter(|c| !(*one).contains(&c.to_string()) && c != ltop).nth(0).unwrap();
        sectors.insert(mid, Segment::Middle);
        // 4. Last one is bot
        let bot = "abcdefg".chars().filter(|c| !sectors.contains_key(c)).nth(0).unwrap();
        sectors.insert(bot, Segment::Bottom);

        // Now lets create the number-segment array
        let mut numbers: Vec<HashSet<Segment>> = vec![
            HashSet::from([Segment::Top, Segment::RightBottom, Segment::RightTop, Segment::LeftBottom, Segment::LeftTop, Segment::Bottom]),
            HashSet::from([Segment::RightTop, Segment::RightBottom]),
            HashSet::from([Segment::Top, Segment::RightTop, Segment::Middle, Segment::LeftBottom, Segment::Bottom]),
            HashSet::from([Segment::Top, Segment::RightTop, Segment::Middle, Segment::RightBottom, Segment::Bottom]),
            HashSet::from([Segment::RightTop, Segment::LeftTop, Segment::Middle, Segment::RightBottom]),
            HashSet::from([Segment::Top, Segment::LeftTop, Segment::Middle, Segment::RightBottom, Segment::Bottom]),
            HashSet::from([Segment::Top, Segment::RightBottom, Segment::LeftBottom, Segment::LeftTop, Segment::Bottom, Segment::Middle]),
            HashSet::from([Segment::Top, Segment::RightTop, Segment::RightBottom]),
            HashSet::from([Segment::Top, Segment::RightBottom, Segment::RightTop, Segment::LeftBottom, Segment::LeftTop, Segment::Bottom, Segment::Middle]),
            HashSet::from([Segment::Top, Segment::RightBottom, Segment::RightTop, Segment::LeftTop, Segment::Bottom, Segment::Middle]),
        ];
        let mut num: i64 = 0;
        for s in &output[i] {
            let numset = s.chars().map(|c| sectors.get(&c).unwrap().clone()).collect::<HashSet<Segment>>();
            for i in 0..numbers.len() {
                if numset == numbers[i] {
                    num *= 10;
                    num += i as i64;
                }
            }
        }
        res += num;
    }
    res
}

fn input_test() -> Vec<Vec<String>> {
    vec![
        vec!["be".to_string(), "cfbegad".to_string(), "cbdgef".to_string(), "fgaecd".to_string(), "cgeb".to_string(), "fdcge".to_string(), "agebfd".to_string(), "fecdb".to_string(), "fabcd".to_string(), "edb".to_string()],
        vec!["edbfga".to_string(), "begcd".to_string(), "cbg".to_string(), "gc".to_string(), "gcadebf".to_string(), "fbgde".to_string(), "acbgfd".to_string(), "abcde".to_string(), "gfcbed".to_string(), "gfec".to_string()],
        vec!["fgaebd".to_string(), "cg".to_string(), "bdaec".to_string(), "gdafb".to_string(), "agbcfd".to_string(), "gdcbef".to_string(), "bgcad".to_string(), "gfac".to_string(), "gcb".to_string(), "cdgabef".to_string()],
        vec!["fbegcd".to_string(), "cbd".to_string(), "adcefb".to_string(), "dageb".to_string(), "afcb".to_string(), "bc".to_string(), "aefdc".to_string(), "ecdab".to_string(), "fgdeca".to_string(), "fcdbega".to_string()],
        vec!["aecbfdg".to_string(), "fbg".to_string(), "gf".to_string(), "bafeg".to_string(), "dbefa".to_string(), "fcge".to_string(), "gcbea".to_string(), "fcaegb".to_string(), "dgceab".to_string(), "fcbdga".to_string()],
        vec!["fgeab".to_string(), "ca".to_string(), "afcebg".to_string(), "bdacfeg".to_string(), "cfaedg".to_string(), "gcfdb".to_string(), "baec".to_string(), "bfadeg".to_string(), "bafgc".to_string(), "acf".to_string()],
        vec!["dbcfg".to_string(), "fgd".to_string(), "bdegcaf".to_string(), "fgec".to_string(), "aegbdf".to_string(), "ecdfab".to_string(), "fbedc".to_string(), "dacgb".to_string(), "gdcebf".to_string(), "gf".to_string()],
        vec!["bdfegc".to_string(), "cbegaf".to_string(), "gecbf".to_string(), "dfcage".to_string(), "bdacg".to_string(), "ed".to_string(), "bedf".to_string(), "ced".to_string(), "adcbefg".to_string(), "gebcd".to_string()],
        vec!["egadfb".to_string(), "cdbfeg".to_string(), "cegd".to_string(), "fecab".to_string(), "cgb".to_string(), "gbdefca".to_string(), "cg".to_string(), "fgcdab".to_string(), "egfdb".to_string(), "bfceg".to_string()],
        vec!["gcafb".to_string(), "gcf".to_string(), "dcaebfg".to_string(), "ecagb".to_string(), "gf".to_string(), "abcdeg".to_string(), "gaef".to_string(), "cafbge".to_string(), "fdbac".to_string(), "fegbdc".to_string()]
    ]
}

fn output_test() -> Vec<Vec<String>> {
    vec![
        vec!["fdgacbe".to_string(), "cefdb".to_string(), "cefbgd".to_string(), "gcbe".to_string()],
        vec!["fcgedb".to_string(), "cgb".to_string(), "dgebacf".to_string(), "gc".to_string()],
        vec!["cg".to_string(), "cg".to_string(), "fdcagb".to_string(), "cbg".to_string()],
        vec!["efabcd".to_string(), "cedba".to_string(), "gadfec".to_string(), "cb".to_string()],
        vec!["gecf".to_string(), "egdcabf".to_string(), "bgf".to_string(), "bfgea".to_string()],
        vec!["gebdcfa".to_string(), "ecba".to_string(), "ca".to_string(), "fadegcb".to_string()],
        vec!["cefg".to_string(), "dcbef".to_string(), "fcge".to_string(), "gbcadfe".to_string()],
        vec!["ed".to_string(), "bcgafe".to_string(), "cdgba".to_string(), "cbgef".to_string()],
        vec!["gbdfcae".to_string(), "bgc".to_string(), "cg".to_string(), "cgb".to_string()],
        vec!["fgae".to_string(), "cfgab".to_string(), "fg".to_string(), "bagce".to_string()]
    ]
}

fn input_source() -> Vec<Vec<String>> {
    vec![
        vec!["cg".to_string(), "fadegbc".to_string(), "ecfadb".to_string(), "acdbeg".to_string(), "abgfe".to_string(), "dcegfb".to_string(), "gcad".to_string(), "bceag".to_string(), "debca".to_string(), "bgc".to_string()],
        vec!["bgeacd".to_string(), "ea".to_string(), "dfcab".to_string(), "fcdgbae".to_string(), "ecbgf".to_string(), "gbcadf".to_string(), "defa".to_string(), "cae".to_string(), "dcaefb".to_string(), "fabce".to_string()],
        vec!["fb".to_string(), "gafbec".to_string(), "dcabe".to_string(), "ecfdag".to_string(), "fagdcb".to_string(), "afcdb".to_string(), "cbf".to_string(), "gdfb".to_string(), "agfdc".to_string(), "acfgdbe".to_string()],
        vec!["fd".to_string(), "bcafe".to_string(), "afed".to_string(), "acbfde".to_string(), "fcbde".to_string(), "fcbgae".to_string(), "fgabdc".to_string(), "edbgfca".to_string(), "cgebd".to_string(), "dfb".to_string()],
        vec!["deacg".to_string(), "egfdbac".to_string(), "agefd".to_string(), "gbedc".to_string(), "gebfca".to_string(), "ac".to_string(), "gadefb".to_string(), "ace".to_string(), "fadc".to_string(), "fcdgae".to_string()],
        vec!["cfaedb".to_string(), "gedfa".to_string(), "fbegd".to_string(), "dgca".to_string(), "ga".to_string(), "dfcae".to_string(), "agf".to_string(), "dfagceb".to_string(), "gdfcae".to_string(), "ecbgaf".to_string()],
        vec!["ceg".to_string(), "gfdcab".to_string(), "dfacge".to_string(), "edgf".to_string(), "fecagb".to_string(), "ecdba".to_string(), "ge".to_string(), "gceda".to_string(), "fcbaged".to_string(), "cgdaf".to_string()],
        vec!["caged".to_string(), "egbdf".to_string(), "edabfg".to_string(), "fbad".to_string(), "fagde".to_string(), "gefbcd".to_string(), "fceabg".to_string(), "afg".to_string(), "fa".to_string(), "cfdagbe".to_string()],
        vec!["dac".to_string(), "egdacf".to_string(), "fcedbg".to_string(), "dabcg".to_string(), "gdfcb".to_string(), "dbaeg".to_string(), "ac".to_string(), "cfdaebg".to_string(), "cafb".to_string(), "afdbcg".to_string()],
        vec!["dbaec".to_string(), "edfac".to_string(), "bdgae".to_string(), "dbcegaf".to_string(), "bc".to_string(), "cba".to_string(), "aecdbf".to_string(), "cebf".to_string(), "gbacfd".to_string(), "facdge".to_string()],
        vec!["gfce".to_string(), "acf".to_string(), "fecda".to_string(), "egfda".to_string(), "gbcfda".to_string(), "fc".to_string(), "gcefda".to_string(), "dbcea".to_string(), "afdbge".to_string(), "dbceagf".to_string()],
        vec!["edfgb".to_string(), "ebf".to_string(), "be".to_string(), "gdcafe".to_string(), "degaf".to_string(), "agfbced".to_string(), "deba".to_string(), "bdafge".to_string(), "dgcbf".to_string(), "cbeagf".to_string()],
        vec!["ebgfd".to_string(), "bfcg".to_string(), "gf".to_string(), "fcgbde".to_string(), "dfbagec".to_string(), "gefcda".to_string(), "fadbce".to_string(), "gef".to_string(), "febdc".to_string(), "edbga".to_string()],
        vec!["gabfec".to_string(), "dcfage".to_string(), "febg".to_string(), "gcaeb".to_string(), "gcf".to_string(), "agbcf".to_string(), "gf".to_string(), "cbafd".to_string(), "cabged".to_string(), "cebfagd".to_string()],
        vec!["fgcedb".to_string(), "fagbe".to_string(), "aecgbd".to_string(), "gbcaf".to_string(), "bef".to_string(), "fade".to_string(), "fagdecb".to_string(), "aebdg".to_string(), "ef".to_string(), "feadbg".to_string()],
        vec!["dgebfc".to_string(), "cebfa".to_string(), "dbf".to_string(), "acfbdg".to_string(), "edbafgc".to_string(), "dgfe".to_string(), "decbf".to_string(), "cdgeb".to_string(), "eadbgc".to_string(), "df".to_string()],
        vec!["febgd".to_string(), "fgaced".to_string(), "bfedacg".to_string(), "bfdgae".to_string(), "fdcgbe".to_string(), "fabed".to_string(), "fcbea".to_string(), "gdba".to_string(), "ad".to_string(), "dae".to_string()],
        vec!["abdgf".to_string(), "adcf".to_string(), "bfdeg".to_string(), "fa".to_string(), "gfecdba".to_string(), "fab".to_string(), "debcag".to_string(), "bcgda".to_string(), "bcafdg".to_string(), "fecgba".to_string()],
        vec!["ecdba".to_string(), "bc".to_string(), "dcfeba".to_string(), "eacgdf".to_string(), "cbegfad".to_string(), "dbcf".to_string(), "begda".to_string(), "fcdae".to_string(), "cebgaf".to_string(), "cab".to_string()],
        vec!["bc".to_string(), "fabcged".to_string(), "bcafg".to_string(), "debfcg".to_string(), "gdfac".to_string(), "fgbea".to_string(), "acfged".to_string(), "bcg".to_string(), "cdba".to_string(), "dgfabc".to_string()],
        vec!["egfadb".to_string(), "ce".to_string(), "fgce".to_string(), "bagdc".to_string(), "gdafce".to_string(), "edabcf".to_string(), "gefad".to_string(), "febdgca".to_string(), "aec".to_string(), "aedcg".to_string()],
        vec!["daegf".to_string(), "gebf".to_string(), "acdbf".to_string(), "be".to_string(), "faedbg".to_string(), "dbe".to_string(), "eabdf".to_string(), "fdabgec".to_string(), "aebdgc".to_string(), "cdefag".to_string()],
        vec!["bafgc".to_string(), "efac".to_string(), "gae".to_string(), "ecgdba".to_string(), "ebgfa".to_string(), "ea".to_string(), "degbf".to_string(), "afebcg".to_string(), "fbacdg".to_string(), "afedgbc".to_string()],
        vec!["gfb".to_string(), "bgacfd".to_string(), "efcbd".to_string(), "bdfeac".to_string(), "bg".to_string(), "efgcb".to_string(), "gcbfed".to_string(), "gcafe".to_string(), "begd".to_string(), "bfdgaec".to_string()],
        vec!["efdbc".to_string(), "abd".to_string(), "afcbegd".to_string(), "dfcba".to_string(), "fbedga".to_string(), "ceafgd".to_string(), "cgab".to_string(), "ba".to_string(), "agdcbf".to_string(), "cdfga".to_string()],
        vec!["fde".to_string(), "fgadc".to_string(), "fgceb".to_string(), "eadcbfg".to_string(), "gebd".to_string(), "agfcbe".to_string(), "ed".to_string(), "fgbdce".to_string(), "cbeadf".to_string(), "egfdc".to_string()],
        vec!["abdcg".to_string(), "gaebfc".to_string(), "cfadebg".to_string(), "cdfbg".to_string(), "cegbf".to_string(), "ebcgdf".to_string(), "dbf".to_string(), "fd".to_string(), "cdfe".to_string(), "fedagb".to_string()],
        vec!["fedbc".to_string(), "gdeacfb".to_string(), "cfbgae".to_string(), "ebacdg".to_string(), "gafc".to_string(), "ca".to_string(), "bgdfae".to_string(), "geabf".to_string(), "eafcb".to_string(), "acb".to_string()],
        vec!["fdega".to_string(), "cefabd".to_string(), "fce".to_string(), "bfdegac".to_string(), "afecbg".to_string(), "fecad".to_string(), "cfadb".to_string(), "debc".to_string(), "ec".to_string(), "dfagcb".to_string()],
        vec!["fab".to_string(), "gaedb".to_string(), "cagbdf".to_string(), "fbce".to_string(), "fecgad".to_string(), "dcfeba".to_string(), "dacfe".to_string(), "fb".to_string(), "fbgaecd".to_string(), "faedb".to_string()],
        vec!["bcega".to_string(), "gbacfe".to_string(), "aecgdbf".to_string(), "gae".to_string(), "cabgd".to_string(), "ebafc".to_string(), "edgcfa".to_string(), "ge".to_string(), "facebd".to_string(), "gefb".to_string()],
        vec!["fgea".to_string(), "acf".to_string(), "af".to_string(), "edbgca".to_string(), "defbc".to_string(), "fegbacd".to_string(), "bagcfe".to_string(), "ecbaf".to_string(), "gdcabf".to_string(), "gaceb".to_string()],
        vec!["ecfgb".to_string(), "cfd".to_string(), "dbcgefa".to_string(), "fcdbe".to_string(), "debaf".to_string(), "cdgefa".to_string(), "cd".to_string(), "cfgdbe".to_string(), "acfgbe".to_string(), "bcdg".to_string()],
        vec!["gdfaec".to_string(), "fdcabe".to_string(), "eb".to_string(), "acbgd".to_string(), "cbe".to_string(), "bfae".to_string(), "facbdeg".to_string(), "cebda".to_string(), "bgfced".to_string(), "cfade".to_string()],
        vec!["efbagd".to_string(), "ebf".to_string(), "fdceba".to_string(), "gfdae".to_string(), "dfgabec".to_string(), "dbgef".to_string(), "bf".to_string(), "fabg".to_string(), "gbcde".to_string(), "dgecaf".to_string()],
        vec!["gcadbef".to_string(), "fgadc".to_string(), "cbd".to_string(), "cb".to_string(), "bcgf".to_string(), "bcfad".to_string(), "dgfcba".to_string(), "edafb".to_string(), "gfdeca".to_string(), "ebdgac".to_string()],
        vec!["defbg".to_string(), "dgbaec".to_string(), "gbe".to_string(), "eg".to_string(), "dabfg".to_string(), "fgdaeb".to_string(), "badfgc".to_string(), "cadgbfe".to_string(), "egaf".to_string(), "debfc".to_string()],
        vec!["caf".to_string(), "gcdabe".to_string(), "bfag".to_string(), "fa".to_string(), "edfbgac".to_string(), "becafd".to_string(), "cbega".to_string(), "edcgf".to_string(), "afceg".to_string(), "faecbg".to_string()],
        vec!["egfcba".to_string(), "dafgcbe".to_string(), "cefga".to_string(), "cdbgae".to_string(), "acfgde".to_string(), "bgcfe".to_string(), "ebfdc".to_string(), "bg".to_string(), "fagb".to_string(), "bcg".to_string()],
        vec!["bgcdefa".to_string(), "bcfged".to_string(), "bf".to_string(), "cadbgf".to_string(), "edbcf".to_string(), "fdb".to_string(), "cebgd".to_string(), "dfcea".to_string(), "gbef".to_string(), "gedbac".to_string()],
        vec!["bdegc".to_string(), "decabgf".to_string(), "agbfce".to_string(), "bdcfg".to_string(), "eagd".to_string(), "gebadc".to_string(), "dfeacb".to_string(), "deb".to_string(), "ed".to_string(), "ebgca".to_string()],
        vec!["eabdf".to_string(), "gedbaf".to_string(), "afcbedg".to_string(), "afcdg".to_string(), "bgd".to_string(), "gbae".to_string(), "gadfb".to_string(), "cefdbg".to_string(), "bfdcea".to_string(), "bg".to_string()],
        vec!["egabdfc".to_string(), "dg".to_string(), "efdcab".to_string(), "bdcef".to_string(), "dgecf".to_string(), "cfgea".to_string(), "dfg".to_string(), "cfedbg".to_string(), "bagdfc".to_string(), "gbde".to_string()],
        vec!["fcge".to_string(), "cf".to_string(), "ecbfad".to_string(), "acfedgb".to_string(), "agdef".to_string(), "fcgda".to_string(), "aefbdg".to_string(), "afc".to_string(), "cagdb".to_string(), "cdafeg".to_string()],
        vec!["cbadge".to_string(), "gdec".to_string(), "efagb".to_string(), "ce".to_string(), "ecb".to_string(), "bagecfd".to_string(), "gbcad".to_string(), "gabec".to_string(), "dfacbe".to_string(), "cgbfad".to_string()],
        vec!["cegbaf".to_string(), "aedcg".to_string(), "acgbed".to_string(), "fadbe".to_string(), "afbcdge".to_string(), "gf".to_string(), "fge".to_string(), "gdeaf".to_string(), "dcgf".to_string(), "cegdaf".to_string()],
        vec!["ebdgf".to_string(), "dcgbfe".to_string(), "cfdabe".to_string(), "afdg".to_string(), "agbefd".to_string(), "ad".to_string(), "daebg".to_string(), "cbadefg".to_string(), "ceabg".to_string(), "ade".to_string()],
        vec!["adbf".to_string(), "decbgf".to_string(), "dbc".to_string(), "agcdbf".to_string(), "cdeabgf".to_string(), "dcagb".to_string(), "eacgbf".to_string(), "abfgc".to_string(), "cgaed".to_string(), "bd".to_string()],
        vec!["bgcaf".to_string(), "fgbae".to_string(), "edbcgfa".to_string(), "cdfba".to_string(), "cbdagf".to_string(), "cg".to_string(), "cga".to_string(), "fgdc".to_string(), "edacgb".to_string(), "bfcdae".to_string()],
        vec!["gbe".to_string(), "gedc".to_string(), "fdgcab".to_string(), "bdgaefc".to_string(), "eg".to_string(), "cageb".to_string(), "ebgadf".to_string(), "acbfe".to_string(), "beagdc".to_string(), "dgacb".to_string()],
        vec!["dcega".to_string(), "abgecf".to_string(), "cgeab".to_string(), "ab".to_string(), "gfedbc".to_string(), "adfbgc".to_string(), "bcgef".to_string(), "bafe".to_string(), "dcafebg".to_string(), "abc".to_string()],
        vec!["dfgebc".to_string(), "cdgef".to_string(), "bc".to_string(), "efagb".to_string(), "bfceg".to_string(), "fgedac".to_string(), "cbf".to_string(), "gcdb".to_string(), "egbacfd".to_string(), "cfdaeb".to_string()],
        vec!["febacg".to_string(), "efgba".to_string(), "ebfdg".to_string(), "aefcb".to_string(), "ag".to_string(), "gba".to_string(), "gacfbed".to_string(), "fagc".to_string(), "edbafc".to_string(), "agbedc".to_string()],
        vec!["cabf".to_string(), "fegacd".to_string(), "bf".to_string(), "ecabgdf".to_string(), "gfb".to_string(), "bdefag".to_string(), "cbdge".to_string(), "dfcbg".to_string(), "agdfc".to_string(), "gbfcda".to_string()],
        vec!["dc".to_string(), "fcd".to_string(), "aecgfd".to_string(), "cgfda".to_string(), "baefgd".to_string(), "cead".to_string(), "fgacbed".to_string(), "cfbdge".to_string(), "eadgf".to_string(), "fgabc".to_string()],
        vec!["fgbaed".to_string(), "aebdgcf".to_string(), "edabg".to_string(), "fdba".to_string(), "faecdg".to_string(), "fgaed".to_string(), "gcbed".to_string(), "ab".to_string(), "cgebfa".to_string(), "gab".to_string()],
        vec!["agdcb".to_string(), "edfbgc".to_string(), "edbca".to_string(), "ae".to_string(), "aeb".to_string(), "aefdgcb".to_string(), "eacf".to_string(), "facedb".to_string(), "agbefd".to_string(), "ebdfc".to_string()],
        vec!["ecf".to_string(), "dgfeb".to_string(), "egac".to_string(), "dacfeg".to_string(), "abcdef".to_string(), "ec".to_string(), "gfebdac".to_string(), "cdgbaf".to_string(), "cdegf".to_string(), "fcdga".to_string()],
        vec!["dcega".to_string(), "def".to_string(), "cfgde".to_string(), "aegfcb".to_string(), "deabfcg".to_string(), "fd".to_string(), "defgba".to_string(), "egbdfc".to_string(), "bfcd".to_string(), "cbfeg".to_string()],
        vec!["gecbf".to_string(), "bcdfaeg".to_string(), "cdfga".to_string(), "fgdcbe".to_string(), "gcfbae".to_string(), "eafb".to_string(), "fagcb".to_string(), "bga".to_string(), "daebcg".to_string(), "ab".to_string()],
        vec!["edfbg".to_string(), "df".to_string(), "dcfbae".to_string(), "edf".to_string(), "bcegf".to_string(), "egfbca".to_string(), "acgfbde".to_string(), "aegdb".to_string(), "dcgf".to_string(), "efdgbc".to_string()],
        vec!["gdbfca".to_string(), "acebgd".to_string(), "cabdf".to_string(), "gebaf".to_string(), "becdgaf".to_string(), "ed".to_string(), "fedc".to_string(), "bdefa".to_string(), "eda".to_string(), "ebcfda".to_string()],
        vec!["eafdgc".to_string(), "gbdc".to_string(), "efadb".to_string(), "cd".to_string(), "abfceg".to_string(), "daebc".to_string(), "dce".to_string(), "afegcdb".to_string(), "gbace".to_string(), "becgda".to_string()],
        vec!["bdaf".to_string(), "cbgfd".to_string(), "fag".to_string(), "fgabc".to_string(), "fa".to_string(), "fcbegd".to_string(), "gedfac".to_string(), "gcaeb".to_string(), "fgdacb".to_string(), "eafbdcg".to_string()],
        vec!["bdafec".to_string(), "fdag".to_string(), "gbfce".to_string(), "dgc".to_string(), "dfgbca".to_string(), "dacbge".to_string(), "cfabd".to_string(), "fgdbc".to_string(), "dg".to_string(), "faedgcb".to_string()],
        vec!["ebdcfga".to_string(), "afedcb".to_string(), "aegdcf".to_string(), "fbeg".to_string(), "cbdag".to_string(), "fg".to_string(), "adfgbe".to_string(), "ebafd".to_string(), "bdfga".to_string(), "afg".to_string()],
        vec!["dgeacbf".to_string(), "gdaf".to_string(), "bagecd".to_string(), "dcefa".to_string(), "caedfg".to_string(), "dac".to_string(), "gcebfa".to_string(), "fgace".to_string(), "dfbce".to_string(), "da".to_string()],
        vec!["bfadecg".to_string(), "ba".to_string(), "gab".to_string(), "bafecg".to_string(), "ecab".to_string(), "dfgca".to_string(), "cgfba".to_string(), "bdcfge".to_string(), "fecgb".to_string(), "fdabge".to_string()],
        vec!["eadcg".to_string(), "efd".to_string(), "cdbf".to_string(), "cfdea".to_string(), "cbedaf".to_string(), "egdafb".to_string(), "cfbaeg".to_string(), "fd".to_string(), "aebfc".to_string(), "adecgfb".to_string()],
        vec!["gdb".to_string(), "cbdaf".to_string(), "cdge".to_string(), "cdaebg".to_string(), "efgdba".to_string(), "egcab".to_string(), "gd".to_string(), "afebcg".to_string(), "gdbca".to_string(), "gaedcbf".to_string()],
        vec!["bdfgac".to_string(), "fgadb".to_string(), "adbgc".to_string(), "fgca".to_string(), "cfgdbe".to_string(), "adbfe".to_string(), "fg".to_string(), "dgbace".to_string(), "bfg".to_string(), "dgabecf".to_string()],
        vec!["gedbfa".to_string(), "cdg".to_string(), "aecgd".to_string(), "edfgca".to_string(), "fbdcage".to_string(), "cd".to_string(), "fgdabc".to_string(), "fedc".to_string(), "dafge".to_string(), "cgbea".to_string()],
        vec!["fdceg".to_string(), "edfcb".to_string(), "gd".to_string(), "febgcd".to_string(), "dgfb".to_string(), "gcd".to_string(), "aefcg".to_string(), "cafebdg".to_string(), "bafdce".to_string(), "debgca".to_string()],
        vec!["adbfe".to_string(), "bgcfda".to_string(), "gefda".to_string(), "gcaed".to_string(), "dagbfce".to_string(), "dbeagc".to_string(), "gaf".to_string(), "gf".to_string(), "gfdeac".to_string(), "cgfe".to_string()],
        vec!["fc".to_string(), "cdf".to_string(), "bcfdeg".to_string(), "dfgaeb".to_string(), "fcgdea".to_string(), "gafc".to_string(), "bdeca".to_string(), "fcbedag".to_string(), "faged".to_string(), "dacfe".to_string()],
        vec!["deagcf".to_string(), "ebagfd".to_string(), "bgafdec".to_string(), "cd".to_string(), "cabeg".to_string(), "bcedaf".to_string(), "dec".to_string(), "cfdg".to_string(), "gadce".to_string(), "adfeg".to_string()],
        vec!["dcgab".to_string(), "ac".to_string(), "fabegc".to_string(), "dcaf".to_string(), "acg".to_string(), "fadbcg".to_string(), "fbgacde".to_string(), "cfdgb".to_string(), "cbgfde".to_string(), "debag".to_string()],
        vec!["fgcead".to_string(), "edbcg".to_string(), "cfaed".to_string(), "dcgef".to_string(), "dfbgcea".to_string(), "gf".to_string(), "badcfg".to_string(), "fdcbae".to_string(), "gfd".to_string(), "fgae".to_string()],
        vec!["begcf".to_string(), "cbf".to_string(), "aebf".to_string(), "fdgacb".to_string(), "gdebac".to_string(), "ceabg".to_string(), "egabfc".to_string(), "gdcfe".to_string(), "ebgfacd".to_string(), "fb".to_string()],
        vec!["efgbcd".to_string(), "febdga".to_string(), "bc".to_string(), "fbegd".to_string(), "befcd".to_string(), "dgafebc".to_string(), "ebc".to_string(), "fgbc".to_string(), "dgabce".to_string(), "caefd".to_string()],
        vec!["eafg".to_string(), "badgec".to_string(), "ecgab".to_string(), "gdcfb".to_string(), "fca".to_string(), "fa".to_string(), "cgabef".to_string(), "fcbag".to_string(), "fbeacd".to_string(), "cegfbda".to_string()],
        vec!["gdfae".to_string(), "fdagbc".to_string(), "fecgab".to_string(), "eg".to_string(), "fadec".to_string(), "abgdef".to_string(), "abgdcfe".to_string(), "dbge".to_string(), "eag".to_string(), "fgadb".to_string()],
        vec!["aegbcf".to_string(), "bfgecad".to_string(), "acgfbd".to_string(), "dabceg".to_string(), "aefbd".to_string(), "gcfd".to_string(), "bgd".to_string(), "gcbfa".to_string(), "dg".to_string(), "dagfb".to_string()],
        vec!["bcgdf".to_string(), "be".to_string(), "gcdeb".to_string(), "egadc".to_string(), "bagecd".to_string(), "ebd".to_string(), "cabe".to_string(), "gdcfeab".to_string(), "badfge".to_string(), "egcafd".to_string()],
        vec!["edbafc".to_string(), "fbdgce".to_string(), "befgc".to_string(), "cge".to_string(), "ebdgac".to_string(), "eg".to_string(), "bdcfe".to_string(), "egfd".to_string(), "caedgbf".to_string(), "bcafg".to_string()],
        vec!["cbadf".to_string(), "af".to_string(), "afc".to_string(), "baef".to_string(), "cfbdg".to_string(), "dcegfba".to_string(), "ebdac".to_string(), "dabgec".to_string(), "acbdfe".to_string(), "afecdg".to_string()],
        vec!["ea".to_string(), "eac".to_string(), "cbgaed".to_string(), "cdbaf".to_string(), "adge".to_string(), "dgfeacb".to_string(), "bdaec".to_string(), "ecbgfa".to_string(), "dgbce".to_string(), "gdbfec".to_string()],
        vec!["bgecfa".to_string(), "abegcfd".to_string(), "fgcad".to_string(), "fgdcae".to_string(), "aedc".to_string(), "dfc".to_string(), "fbdga".to_string(), "cd".to_string(), "defgcb".to_string(), "cegaf".to_string()],
        vec!["becfdg".to_string(), "abgcdf".to_string(), "abgec".to_string(), "dafceg".to_string(), "gcdbf".to_string(), "bfgadec".to_string(), "af".to_string(), "fac".to_string(), "abdf".to_string(), "fcgba".to_string()],
        vec!["cbe".to_string(), "ec".to_string(), "caefgdb".to_string(), "cbgeaf".to_string(), "ecbdag".to_string(), "bcadfg".to_string(), "cdae".to_string(), "cbgad".to_string(), "defbg".to_string(), "egdcb".to_string()],
        vec!["aecfbg".to_string(), "cegdfab".to_string(), "fdace".to_string(), "ecd".to_string(), "cd".to_string(), "gadc".to_string(), "cgdaef".to_string(), "efgca".to_string(), "gdfebc".to_string(), "badfe".to_string()],
        vec!["bafgdec".to_string(), "gcd".to_string(), "gacdf".to_string(), "gbcaf".to_string(), "cd".to_string(), "cgfeab".to_string(), "dgbeac".to_string(), "bcfd".to_string(), "abcgfd".to_string(), "fdage".to_string()],
        vec!["gadfec".to_string(), "gfadbce".to_string(), "gceba".to_string(), "abcdf".to_string(), "gd".to_string(), "bdeg".to_string(), "cebgda".to_string(), "cdg".to_string(), "afbecg".to_string(), "bgdac".to_string()],
        vec!["fc".to_string(), "defc".to_string(), "cdeab".to_string(), "bdcgae".to_string(), "acebf".to_string(), "caf".to_string(), "cgefbad".to_string(), "efdbca".to_string(), "gdfacb".to_string(), "bfgea".to_string()],
        vec!["fecab".to_string(), "adfgbe".to_string(), "ecad".to_string(), "ca".to_string(), "adbfec".to_string(), "cab".to_string(), "cdfegba".to_string(), "gcadbf".to_string(), "gbfec".to_string(), "eadfb".to_string()],
        vec!["gbaefd".to_string(), "cafged".to_string(), "feac".to_string(), "cegdb".to_string(), "eafdbgc".to_string(), "ea".to_string(), "agfcd".to_string(), "dgace".to_string(), "bagdfc".to_string(), "ead".to_string()],
        vec!["cbaedf".to_string(), "dfbcga".to_string(), "cbagd".to_string(), "cbfadeg".to_string(), "fdbeag".to_string(), "bgfad".to_string(), "cdgbe".to_string(), "ca".to_string(), "acb".to_string(), "gacf".to_string()],
        vec!["efgc".to_string(), "fg".to_string(), "agbdcf".to_string(), "bdfce".to_string(), "bacdgef".to_string(), "dgfbe".to_string(), "gdfceb".to_string(), "fbg".to_string(), "edfbac".to_string(), "eadbg".to_string()],
        vec!["bdgea".to_string(), "gbcf".to_string(), "facegb".to_string(), "acdfbeg".to_string(), "ebgaf".to_string(), "dabecf".to_string(), "bf".to_string(), "gfeac".to_string(), "aegcfd".to_string(), "fba".to_string()],
        vec!["fedcgab".to_string(), "fceab".to_string(), "cgab".to_string(), "egbdfa".to_string(), "cgaebf".to_string(), "cefdag".to_string(), "fca".to_string(), "fcebd".to_string(), "ac".to_string(), "begfa".to_string()],
        vec!["bfda".to_string(), "gbcadef".to_string(), "bgecd".to_string(), "dafegb".to_string(), "daefg".to_string(), "aecdfg".to_string(), "bgdfe".to_string(), "acbfeg".to_string(), "bf".to_string(), "ebf".to_string()],
        vec!["bacdfge".to_string(), "aegdf".to_string(), "ebgdf".to_string(), "fcaeg".to_string(), "edcgfa".to_string(), "fbecga".to_string(), "ceda".to_string(), "adf".to_string(), "fabdgc".to_string(), "ad".to_string()],
        vec!["abdef".to_string(), "gaedcf".to_string(), "afdgeb".to_string(), "becadgf".to_string(), "edabc".to_string(), "bcdeg".to_string(), "bafcde".to_string(), "acfb".to_string(), "ca".to_string(), "cda".to_string()],
        vec!["efgd".to_string(), "fcgbea".to_string(), "gbadcef".to_string(), "dcabe".to_string(), "fe".to_string(), "aebdfg".to_string(), "fdabgc".to_string(), "abfed".to_string(), "feb".to_string(), "agdfb".to_string()],
        vec!["dcabegf".to_string(), "gedac".to_string(), "ecgfd".to_string(), "cea".to_string(), "gfcebd".to_string(), "agdbe".to_string(), "ac".to_string(), "gcfa".to_string(), "fbeacd".to_string(), "gdecaf".to_string()],
        vec!["bacdgf".to_string(), "dgce".to_string(), "ec".to_string(), "cafdeb".to_string(), "fcega".to_string(), "eca".to_string(), "cdafg".to_string(), "ebagf".to_string(), "degfca".to_string(), "bdfcega".to_string()],
        vec!["gefac".to_string(), "egabcfd".to_string(), "gfc".to_string(), "baecgd".to_string(), "eabcgf".to_string(), "dafec".to_string(), "gf".to_string(), "cbage".to_string(), "acgfbd".to_string(), "egbf".to_string()],
        vec!["gbcaf".to_string(), "dcaefb".to_string(), "gdec".to_string(), "adfeg".to_string(), "acefdbg".to_string(), "fbdage".to_string(), "cdfag".to_string(), "acefdg".to_string(), "cd".to_string(), "dca".to_string()],
        vec!["fbadge".to_string(), "bdcg".to_string(), "acb".to_string(), "caebfd".to_string(), "bgead".to_string(), "gbcdea".to_string(), "caebg".to_string(), "dbgcaef".to_string(), "gfeca".to_string(), "cb".to_string()],
        vec!["bcd".to_string(), "agdce".to_string(), "edbagf".to_string(), "gfdecb".to_string(), "cbfa".to_string(), "bc".to_string(), "debafc".to_string(), "aedfb".to_string(), "beacdgf".to_string(), "cbead".to_string()],
        vec!["bag".to_string(), "ab".to_string(), "ebca".to_string(), "dabecg".to_string(), "agcde".to_string(), "dbfagce".to_string(), "efgcad".to_string(), "gbcdaf".to_string(), "egdab".to_string(), "egfbd".to_string()],
        vec!["gbcadf".to_string(), "cdabg".to_string(), "bd".to_string(), "dbg".to_string(), "afgbedc".to_string(), "fdgca".to_string(), "gacbe".to_string(), "adcfge".to_string(), "cfbd".to_string(), "gedabf".to_string()],
        vec!["cfeabd".to_string(), "cabgf".to_string(), "gadfeb".to_string(), "gbadc".to_string(), "dcbgae".to_string(), "dgec".to_string(), "bdage".to_string(), "gbfcade".to_string(), "cd".to_string(), "dcb".to_string()],
        vec!["bcdfg".to_string(), "gdfeab".to_string(), "abecdgf".to_string(), "edg".to_string(), "gefca".to_string(), "ecadgf".to_string(), "fedcg".to_string(), "deca".to_string(), "ed".to_string(), "gcbefa".to_string()],
        vec!["acbgfd".to_string(), "bdgcf".to_string(), "dcfga".to_string(), "fbd".to_string(), "dfbcgea".to_string(), "fb".to_string(), "dbgec".to_string(), "eafbcd".to_string(), "fbga".to_string(), "efagcd".to_string()],
        vec!["dafecb".to_string(), "acedg".to_string(), "bc".to_string(), "dgafce".to_string(), "gbeac".to_string(), "fgceabd".to_string(), "bce".to_string(), "gbefa".to_string(), "gdbc".to_string(), "dbceag".to_string()],
        vec!["fgadce".to_string(), "db".to_string(), "fbadg".to_string(), "deagcfb".to_string(), "abd".to_string(), "aegbf".to_string(), "gcdbfa".to_string(), "fgdac".to_string(), "gbaedc".to_string(), "bdfc".to_string()],
        vec!["bdga".to_string(), "fbagc".to_string(), "ceadbf".to_string(), "ecgdfba".to_string(), "bfgce".to_string(), "fga".to_string(), "cbfagd".to_string(), "ga".to_string(), "cfdab".to_string(), "gecdaf".to_string()],
        vec!["fce".to_string(), "fcdg".to_string(), "adfgeb".to_string(), "cegadf".to_string(), "bafdce".to_string(), "fecga".to_string(), "fc".to_string(), "becga".to_string(), "dafebcg".to_string(), "agfde".to_string()],
        vec!["cegdba".to_string(), "fb".to_string(), "bcdeg".to_string(), "fecb".to_string(), "gdeaf".to_string(), "acgfdb".to_string(), "fdb".to_string(), "fgdbe".to_string(), "cbdafeg".to_string(), "gecbdf".to_string()],
        vec!["eg".to_string(), "feadcb".to_string(), "dgec".to_string(), "egf".to_string(), "afedc".to_string(), "eabgfc".to_string(), "gaedf".to_string(), "bdgaf".to_string(), "acdgbfe".to_string(), "egafdc".to_string()],
        vec!["bg".to_string(), "dagfe".to_string(), "edfcabg".to_string(), "dbgcae".to_string(), "fgaedb".to_string(), "fbag".to_string(), "fdcage".to_string(), "dgb".to_string(), "bfegd".to_string(), "cbdef".to_string()],
        vec!["dabgfc".to_string(), "acefbd".to_string(), "cegad".to_string(), "cbeda".to_string(), "bac".to_string(), "adbef".to_string(), "cb".to_string(), "bcfe".to_string(), "fbgdea".to_string(), "cafbegd".to_string()],
        vec!["gfbca".to_string(), "decbfa".to_string(), "ecadbg".to_string(), "cga".to_string(), "gc".to_string(), "cfdg".to_string(), "bfcadg".to_string(), "bfeadgc".to_string(), "cfabd".to_string(), "efgba".to_string()],
        vec!["gcbead".to_string(), "fadbge".to_string(), "befc".to_string(), "bgfceda".to_string(), "dbcea".to_string(), "cbefda".to_string(), "bfa".to_string(), "gfacd".to_string(), "bf".to_string(), "facbd".to_string()],
        vec!["baedc".to_string(), "feag".to_string(), "begafc".to_string(), "fcagdb".to_string(), "eg".to_string(), "bagcefd".to_string(), "baceg".to_string(), "gce".to_string(), "bcgdfe".to_string(), "cfabg".to_string()],
        vec!["ecab".to_string(), "ce".to_string(), "bfcdg".to_string(), "fabgce".to_string(), "efdcag".to_string(), "cgfeb".to_string(), "gbaedf".to_string(), "dfegbca".to_string(), "cef".to_string(), "baegf".to_string()],
        vec!["beacfg".to_string(), "fg".to_string(), "efg".to_string(), "ebfcd".to_string(), "dbfgcae".to_string(), "fbga".to_string(), "bgcea".to_string(), "cefgad".to_string(), "cgbfe".to_string(), "ceagbd".to_string()],
        vec!["cebdfg".to_string(), "ba".to_string(), "abf".to_string(), "bdgfaec".to_string(), "aebcfg".to_string(), "gfcdb".to_string(), "dbga".to_string(), "afdcb".to_string(), "gcbadf".to_string(), "fecad".to_string()],
        vec!["gceaf".to_string(), "ebf".to_string(), "eadb".to_string(), "abdcf".to_string(), "adfebc".to_string(), "fdbceg".to_string(), "cgafdb".to_string(), "efcab".to_string(), "cefdgab".to_string(), "be".to_string()],
        vec!["fgbcda".to_string(), "bceag".to_string(), "dfabge".to_string(), "fbdceg".to_string(), "fced".to_string(), "bgfdc".to_string(), "fabgdce".to_string(), "fe".to_string(), "gfe".to_string(), "cgbef".to_string()],
        vec!["deagcf".to_string(), "bdfacg".to_string(), "fcbad".to_string(), "dca".to_string(), "gfdbc".to_string(), "ecgbadf".to_string(), "febcdg".to_string(), "dbafe".to_string(), "bcga".to_string(), "ac".to_string()],
        vec!["dbceg".to_string(), "bcg".to_string(), "gfbeca".to_string(), "cgfbaed".to_string(), "egfcbd".to_string(), "ebgfd".to_string(), "gcfd".to_string(), "cg".to_string(), "bdaegf".to_string(), "decab".to_string()],
        vec!["cfbed".to_string(), "bdae".to_string(), "dfcgb".to_string(), "ed".to_string(), "efbca".to_string(), "cde".to_string(), "fcbdae".to_string(), "gbcfae".to_string(), "fbdgaec".to_string(), "aefdgc".to_string()],
        vec!["ed".to_string(), "dfce".to_string(), "dae".to_string(), "bedca".to_string(), "gfaedb".to_string(), "befdac".to_string(), "bacgd".to_string(), "eabgcf".to_string(), "bfcae".to_string(), "agdfbec".to_string()],
        vec!["dagcb".to_string(), "cbge".to_string(), "daefbc".to_string(), "bgadfce".to_string(), "bc".to_string(), "cfgad".to_string(), "abdefg".to_string(), "gbdea".to_string(), "cab".to_string(), "cabegd".to_string()],
        vec!["ac".to_string(), "fgdca".to_string(), "gfbdca".to_string(), "bcgdafe".to_string(), "cefdg".to_string(), "cgbeda".to_string(), "cda".to_string(), "gaefdb".to_string(), "fbac".to_string(), "dgfba".to_string()],
        vec!["fedgc".to_string(), "dbcaf".to_string(), "ceb".to_string(), "adefgc".to_string(), "ebdg".to_string(), "acgbef".to_string(), "cbefdg".to_string(), "be".to_string(), "befcd".to_string(), "dcfaegb".to_string()],
        vec!["aefcd".to_string(), "fcgaeb".to_string(), "eacdgfb".to_string(), "fbcg".to_string(), "aebdgc".to_string(), "gdbeaf".to_string(), "agfbe".to_string(), "agc".to_string(), "cgaef".to_string(), "cg".to_string()],
        vec!["af".to_string(), "bdeag".to_string(), "gfbdace".to_string(), "fga".to_string(), "bcaedg".to_string(), "cdegf".to_string(), "feab".to_string(), "eafdg".to_string(), "gfedab".to_string(), "dagcfb".to_string()],
        vec!["dgafc".to_string(), "adfcebg".to_string(), "fagec".to_string(), "dacfeg".to_string(), "fgd".to_string(), "fd".to_string(), "gbdac".to_string(), "defc".to_string(), "fdaegb".to_string(), "gafbce".to_string()],
        vec!["bacfdg".to_string(), "dgc".to_string(), "cg".to_string(), "bcaed".to_string(), "adcgb".to_string(), "cafdeg".to_string(), "bgcf".to_string(), "dgfab".to_string(), "bgfead".to_string(), "cbfaged".to_string()],
        vec!["agfebd".to_string(), "cb".to_string(), "bafecg".to_string(), "efbga".to_string(), "edgac".to_string(), "gfedcb".to_string(), "cedfagb".to_string(), "afbc".to_string(), "gcb".to_string(), "acgeb".to_string()],
        vec!["fgdae".to_string(), "edfbca".to_string(), "bgdf".to_string(), "gceaf".to_string(), "eabfdg".to_string(), "aebfd".to_string(), "gad".to_string(), "defbgca".to_string(), "gdceab".to_string(), "dg".to_string()],
        vec!["befadcg".to_string(), "gdfa".to_string(), "afdeb".to_string(), "aebfg".to_string(), "fg".to_string(), "bcfead".to_string(), "gadfbe".to_string(), "gfe".to_string(), "cgeab".to_string(), "gfbdce".to_string()],
        vec!["cb".to_string(), "cbg".to_string(), "gbaedc".to_string(), "efbga".to_string(), "bcafgd".to_string(), "caefdbg".to_string(), "efcdga".to_string(), "eacgd".to_string(), "bcde".to_string(), "gbcea".to_string()],
        vec!["cdaebfg".to_string(), "edcbg".to_string(), "cgedba".to_string(), "acbeg".to_string(), "fbdgc".to_string(), "edg".to_string(), "fagebc".to_string(), "cdea".to_string(), "ed".to_string(), "abedfg".to_string()],
        vec!["eafbg".to_string(), "acebgdf".to_string(), "dagcb".to_string(), "eadc".to_string(), "ecg".to_string(), "ce".to_string(), "cfbgda".to_string(), "cegba".to_string(), "dgbace".to_string(), "bfedgc".to_string()],
        vec!["egafcd".to_string(), "gdfaceb".to_string(), "acegf".to_string(), "cgda".to_string(), "deg".to_string(), "dgfbea".to_string(), "gd".to_string(), "cdfge".to_string(), "feabcg".to_string(), "cedfb".to_string()],
        vec!["feag".to_string(), "eg".to_string(), "aebfc".to_string(), "efcadb".to_string(), "bge".to_string(), "cdbgf".to_string(), "fgbcead".to_string(), "bdegac".to_string(), "ebcfg".to_string(), "aefbcg".to_string()],
        vec!["beac".to_string(), "bdgea".to_string(), "ebagdc".to_string(), "bdgafc".to_string(), "bcagd".to_string(), "age".to_string(), "bcgdeaf".to_string(), "ae".to_string(), "dfaecg".to_string(), "defbg".to_string()],
        vec!["ca".to_string(), "agdbec".to_string(), "abc".to_string(), "dbgfca".to_string(), "gbfecd".to_string(), "cbfgd".to_string(), "acgf".to_string(), "fbdae".to_string(), "fdacb".to_string(), "ceafbgd".to_string()],
        vec!["bgadf".to_string(), "cdgbefa".to_string(), "bagef".to_string(), "bfe".to_string(), "agfdce".to_string(), "cebg".to_string(), "ecbadf".to_string(), "gbecaf".to_string(), "eb".to_string(), "egcaf".to_string()],
        vec!["bfgcea".to_string(), "fdgeca".to_string(), "cae".to_string(), "gbeca".to_string(), "abcf".to_string(), "cfebagd".to_string(), "ca".to_string(), "fgdbae".to_string(), "cebgd".to_string(), "faebg".to_string()],
        vec!["cage".to_string(), "dfgaebc".to_string(), "ae".to_string(), "gfbed".to_string(), "ebgaf".to_string(), "decabf".to_string(), "afbcg".to_string(), "bfacdg".to_string(), "aef".to_string(), "cbaegf".to_string()],
        vec!["bcegdf".to_string(), "cgdafb".to_string(), "abfd".to_string(), "abgcfe".to_string(), "fdg".to_string(), "gfdac".to_string(), "gefbcda".to_string(), "dgeac".to_string(), "afcgb".to_string(), "fd".to_string()],
        vec!["cgdbe".to_string(), "decba".to_string(), "bfdgcea".to_string(), "debfa".to_string(), "cfdbae".to_string(), "gafedb".to_string(), "ac".to_string(), "fbca".to_string(), "agfdec".to_string(), "cea".to_string()],
        vec!["gacdef".to_string(), "bfeda".to_string(), "afecd".to_string(), "gfbae".to_string(), "bdcega".to_string(), "bafgcde".to_string(), "dab".to_string(), "dfceba".to_string(), "bcfd".to_string(), "db".to_string()],
        vec!["abdgcf".to_string(), "dafec".to_string(), "faedb".to_string(), "cf".to_string(), "bcfgeda".to_string(), "gefbad".to_string(), "cabfde".to_string(), "cfbe".to_string(), "afc".to_string(), "aegdc".to_string()],
        vec!["aedcb".to_string(), "fce".to_string(), "bedfc".to_string(), "cfbged".to_string(), "gefb".to_string(), "bgfeacd".to_string(), "edgacf".to_string(), "ef".to_string(), "gcfdb".to_string(), "dgfabc".to_string()],
        vec!["dbfagec".to_string(), "dabec".to_string(), "eda".to_string(), "fdcbea".to_string(), "ed".to_string(), "agdbc".to_string(), "gfbcea".to_string(), "cbefa".to_string(), "efdb".to_string(), "gfdeca".to_string()],
        vec!["dafbe".to_string(), "adfbcg".to_string(), "bfeac".to_string(), "cbe".to_string(), "bagfecd".to_string(), "cfge".to_string(), "egcdab".to_string(), "cgabf".to_string(), "ce".to_string(), "gfceab".to_string()],
        vec!["agc".to_string(), "ag".to_string(), "gbaecf".to_string(), "cagbf".to_string(), "fgdcaeb".to_string(), "bdgfc".to_string(), "cefab".to_string(), "ecfagd".to_string(), "bega".to_string(), "aedfcb".to_string()],
        vec!["ea".to_string(), "gfbda".to_string(), "eacd".to_string(), "bfced".to_string(), "eagfbc".to_string(), "aeb".to_string(), "cbfged".to_string(), "befda".to_string(), "bgafced".to_string(), "dacfeb".to_string()],
        vec!["gcbadf".to_string(), "gbead".to_string(), "afcbde".to_string(), "gad".to_string(), "beadf".to_string(), "daefgb".to_string(), "aecgb".to_string(), "dg".to_string(), "efagdcb".to_string(), "gedf".to_string()],
        vec!["dbc".to_string(), "fdcge".to_string(), "dabeg".to_string(), "aceb".to_string(), "cgdeb".to_string(), "afedbg".to_string(), "cdgeba".to_string(), "bdagcfe".to_string(), "bc".to_string(), "gcdbaf".to_string()],
        vec!["bfcd".to_string(), "ebfgd".to_string(), "cgf".to_string(), "egcab".to_string(), "bfdcge".to_string(), "adfgec".to_string(), "gbefad".to_string(), "fcbegad".to_string(), "gfebc".to_string(), "cf".to_string()],
        vec!["bcfedga".to_string(), "df".to_string(), "dfa".to_string(), "gcaedb".to_string(), "fagcbd".to_string(), "adecbf".to_string(), "ecgaf".to_string(), "dgfb".to_string(), "gcdaf".to_string(), "bdcag".to_string()],
        vec!["acf".to_string(), "cdfe".to_string(), "dcbegaf".to_string(), "feabd".to_string(), "ecbgfa".to_string(), "dbacg".to_string(), "aebgfd".to_string(), "bfdeac".to_string(), "dcfba".to_string(), "fc".to_string()],
        vec!["ecf".to_string(), "bgaecd".to_string(), "ecdgfb".to_string(), "adgfe".to_string(), "egcfa".to_string(), "fcbedga".to_string(), "bagec".to_string(), "gacebf".to_string(), "cafb".to_string(), "fc".to_string()],
        vec!["beagc".to_string(), "aegbdc".to_string(), "fcdeb".to_string(), "fcgbe".to_string(), "gf".to_string(), "geaf".to_string(), "acgbfd".to_string(), "fcg".to_string(), "fecgdba".to_string(), "fbgeca".to_string()],
        vec!["gedf".to_string(), "caebfd".to_string(), "fcgea".to_string(), "bdcgae".to_string(), "age".to_string(), "acefd".to_string(), "fdcagbe".to_string(), "gacfb".to_string(), "gcefda".to_string(), "eg".to_string()],
        vec!["gceabfd".to_string(), "cdgba".to_string(), "cgfdae".to_string(), "cfdagb".to_string(), "begd".to_string(), "ceabg".to_string(), "ceafb".to_string(), "ge".to_string(), "gae".to_string(), "gabdce".to_string()],
        vec!["deg".to_string(), "cegdbf".to_string(), "dbceg".to_string(), "bdgafe".to_string(), "baegdfc".to_string(), "bcadg".to_string(), "de".to_string(), "agbecf".to_string(), "gfbec".to_string(), "ecfd".to_string()],
        vec!["afgced".to_string(), "gb".to_string(), "dbg".to_string(), "gbec".to_string(), "badcfg".to_string(), "abged".to_string(), "baedf".to_string(), "eadcg".to_string(), "cafgedb".to_string(), "gdbeca".to_string()],
        vec!["ad".to_string(), "bdegca".to_string(), "cgabd".to_string(), "bedfgac".to_string(), "gda".to_string(), "cead".to_string(), "bfcaeg".to_string(), "gaecb".to_string(), "cdbfg".to_string(), "edgabf".to_string()],
        vec!["bacd".to_string(), "afgecd".to_string(), "ba".to_string(), "eadbcf".to_string(), "fdgeb".to_string(), "bgacef".to_string(), "feagcdb".to_string(), "bfdae".to_string(), "deacf".to_string(), "eba".to_string()],
        vec!["cdafe".to_string(), "dab".to_string(), "febdga".to_string(), "fcbd".to_string(), "fceadb".to_string(), "bd".to_string(), "fecdag".to_string(), "agceb".to_string(), "abdcfeg".to_string(), "bacde".to_string()],
        vec!["ecbgad".to_string(), "cbe".to_string(), "bdef".to_string(), "dfegcb".to_string(), "dgbcf".to_string(), "agcfe".to_string(), "fgebc".to_string(), "eb".to_string(), "fdgbca".to_string(), "ebgadcf".to_string()],
        vec!["cdg".to_string(), "dabfc".to_string(), "edbfac".to_string(), "gd".to_string(), "fegac".to_string(), "dfacg".to_string(), "gfdb".to_string(), "deabcfg".to_string(), "dbacge".to_string(), "bcadgf".to_string()],
        vec!["adcfe".to_string(), "afd".to_string(), "deagcf".to_string(), "faebc".to_string(), "ebfcagd".to_string(), "efdg".to_string(), "cbeagd".to_string(), "gabfcd".to_string(), "fd".to_string(), "cedga".to_string()],
        vec!["dgfc".to_string(), "cabfe".to_string(), "bcg".to_string(), "abegdf".to_string(), "gdafb".to_string(), "cg".to_string(), "afbecgd".to_string(), "fcagbd".to_string(), "aedgcb".to_string(), "bfgac".to_string()],
        vec!["fbadge".to_string(), "bfgca".to_string(), "agf".to_string(), "dacbfge".to_string(), "bdcafe".to_string(), "bfeac".to_string(), "aegc".to_string(), "ga".to_string(), "fabgce".to_string(), "dfgcb".to_string()],
        vec!["abe".to_string(), "ebcfga".to_string(), "dgabc".to_string(), "gfcbe".to_string(), "fcadbeg".to_string(), "gafe".to_string(), "ea".to_string(), "gcabe".to_string(), "fdgbce".to_string(), "aecfbd".to_string()],
        vec!["gd".to_string(), "ebacfd".to_string(), "afedcgb".to_string(), "cdeabg".to_string(), "cabgd".to_string(), "gad".to_string(), "aecbd".to_string(), "ecdg".to_string(), "gdbfae".to_string(), "bacgf".to_string()],
        vec!["ec".to_string(), "dgfae".to_string(), "gfdcba".to_string(), "ced".to_string(), "dagebc".to_string(), "dcafbe".to_string(), "cadfb".to_string(), "efacd".to_string(), "edgfabc".to_string(), "cefb".to_string()],
        vec!["ec".to_string(), "cfed".to_string(), "gbafe".to_string(), "gfecdba".to_string(), "cfdgae".to_string(), "cae".to_string(), "gfdac".to_string(), "gacbde".to_string(), "fdcagb".to_string(), "ecfag".to_string()],
        vec!["acge".to_string(), "fgebd".to_string(), "fcbeg".to_string(), "agfcbe".to_string(), "ce".to_string(), "bcfga".to_string(), "cbe".to_string(), "eabgfcd".to_string(), "gcdafb".to_string(), "edfbca".to_string()],
        vec!["eafgcb".to_string(), "bface".to_string(), "dcgebfa".to_string(), "dbface".to_string(), "dc".to_string(), "ecadbg".to_string(), "acfd".to_string(), "fdebg".to_string(), "dcefb".to_string(), "bdc".to_string()],
        vec!["cdbgae".to_string(), "befcg".to_string(), "bgade".to_string(), "fgbeacd".to_string(), "gbdfae".to_string(), "fbdacg".to_string(), "fd".to_string(), "dfg".to_string(), "aedf".to_string(), "bfgde".to_string()],
        vec!["dcage".to_string(), "bcae".to_string(), "agdfcb".to_string(), "efbagd".to_string(), "bdafceg".to_string(), "gfecd".to_string(), "dae".to_string(), "dbecga".to_string(), "dgcba".to_string(), "ae".to_string()],
        vec!["fbedcag".to_string(), "agfe".to_string(), "cbeafd".to_string(), "efgbc".to_string(), "gacbd".to_string(), "agefbc".to_string(), "af".to_string(), "cagbf".to_string(), "cedbfg".to_string(), "afc".to_string()],
        vec!["abecgdf".to_string(), "cagbd".to_string(), "efbdc".to_string(), "ebfg".to_string(), "fg".to_string(), "gdfcb".to_string(), "aecdgf".to_string(), "dbgcfe".to_string(), "cbafde".to_string(), "gdf".to_string()],
        vec!["ecbafd".to_string(), "ba".to_string(), "bafdeg".to_string(), "fgdba".to_string(), "dba".to_string(), "fgebd".to_string(), "cbefgd".to_string(), "bgae".to_string(), "dcgfa".to_string(), "daegcbf".to_string()],
        vec!["egbdc".to_string(), "acbfged".to_string(), "gae".to_string(), "cdaeg".to_string(), "ga".to_string(), "agbefd".to_string(), "acgf".to_string(), "decaf".to_string(), "cdaegf".to_string(), "eafdcb".to_string()],
        vec!["bafce".to_string(), "adcfeg".to_string(), "caegfb".to_string(), "cefga".to_string(), "fb".to_string(), "fab".to_string(), "bdcagfe".to_string(), "dabgef".to_string(), "bgcf".to_string(), "ebdac".to_string()],
        vec!["gcedab".to_string(), "facgbd".to_string(), "efadg".to_string(), "edacg".to_string(), "bdafecg".to_string(), "fedgb".to_string(), "fda".to_string(), "af".to_string(), "aefc".to_string(), "gafcde".to_string()],
        vec!["gdba".to_string(), "gedfb".to_string(), "egfbad".to_string(), "fegadc".to_string(), "ecgfba".to_string(), "dfbec".to_string(), "gd".to_string(), "cbedfga".to_string(), "abefg".to_string(), "fdg".to_string()],
        vec!["fbdec".to_string(), "fdbceag".to_string(), "feacb".to_string(), "fbcgd".to_string(), "dcbfge".to_string(), "dec".to_string(), "efgadc".to_string(), "dcbafg".to_string(), "ed".to_string(), "dbge".to_string()],
        vec!["cbgaed".to_string(), "fbagc".to_string(), "cbfd".to_string(), "bdaegf".to_string(), "bdcag".to_string(), "egdbfac".to_string(), "afgce".to_string(), "bcfadg".to_string(), "baf".to_string(), "bf".to_string()]
    ]
}

fn output_source() -> Vec<Vec<String>> {
    vec![
        vec!["ceafbd".to_string(), "gfedcb".to_string(), "cabedf".to_string(), "dbace".to_string()],
        vec!["ea".to_string(), "fdae".to_string(), "daecgb".to_string(), "cea".to_string()],
        vec!["acdgfb".to_string(), "gdcfa".to_string(), "bceda".to_string(), "bf".to_string()],
        vec!["dbf".to_string(), "becgd".to_string(), "bfd".to_string(), "efcdb".to_string()],
        vec!["gabfde".to_string(), "cbdgfae".to_string(), "ca".to_string(), "eca".to_string()],
        vec!["gaecfb".to_string(), "cdag".to_string(), "gfa".to_string(), "gaf".to_string()],
        vec!["gdaecf".to_string(), "gceda".to_string(), "fbacge".to_string(), "dcagf".to_string()],
        vec!["bfdge".to_string(), "degca".to_string(), "fbda".to_string(), "af".to_string()],
        vec!["decagf".to_string(), "ebdag".to_string(), "bfdgce".to_string(), "fdbgec".to_string()],
        vec!["efbc".to_string(), "cab".to_string(), "ecabfdg".to_string(), "cab".to_string()],
        vec!["bfedgac".to_string(), "bfegda".to_string(), "fcgdab".to_string(), "fecg".to_string()],
        vec!["efb".to_string(), "dbcgf".to_string(), "dgabef".to_string(), "be".to_string()],
        vec!["gf".to_string(), "dgbefc".to_string(), "gfe".to_string(), "bedfac".to_string()],
        vec!["egbf".to_string(), "fg".to_string(), "gcdbea".to_string(), "dfbac".to_string()],
        vec!["abdge".to_string(), "abfdge".to_string(), "abcgf".to_string(), "gabedc".to_string()],
        vec!["bgdcefa".to_string(), "caebf".to_string(), "fbd".to_string(), "adfbgc".to_string()],
        vec!["dae".to_string(), "agbd".to_string(), "gbfdea".to_string(), "aegcfd".to_string()],
        vec!["edbfg".to_string(), "gcfdeab".to_string(), "bgfda".to_string(), "dfebg".to_string()],
        vec!["abc".to_string(), "bc".to_string(), "ecfdab".to_string(), "cab".to_string()],
        vec!["baefg".to_string(), "fbcag".to_string(), "begcfad".to_string(), "dabc".to_string()],
        vec!["aefbdg".to_string(), "ec".to_string(), "ceadg".to_string(), "gecad".to_string()],
        vec!["be".to_string(), "gfdeac".to_string(), "bdfac".to_string(), "gdbace".to_string()],
        vec!["acfe".to_string(), "age".to_string(), "dbfecag".to_string(), "bafgc".to_string()],
        vec!["cbgef".to_string(), "gcfea".to_string(), "fbcdae".to_string(), "faedgbc".to_string()],
        vec!["dcafg".to_string(), "cabdf".to_string(), "ab".to_string(), "bcga".to_string()],
        vec!["bdgcfae".to_string(), "fde".to_string(), "edgb".to_string(), "gbde".to_string()],
        vec!["dgbca".to_string(), "cgfeadb".to_string(), "gdfaeb".to_string(), "beagdf".to_string()],
        vec!["bafge".to_string(), "aefcgb".to_string(), "cfbae".to_string(), "defbc".to_string()],
        vec!["dcbaf".to_string(), "gebfcda".to_string(), "fce".to_string(), "fegad".to_string()],
        vec!["dbecfa".to_string(), "gefcdab".to_string(), "bfa".to_string(), "efbad".to_string()],
        vec!["baecf".to_string(), "efacdb".to_string(), "ebagdcf".to_string(), "fgeb".to_string()],
        vec!["aebfc".to_string(), "abgfec".to_string(), "aegf".to_string(), "dcfgab".to_string()],
        vec!["bcgd".to_string(), "fdbea".to_string(), "dcfgbe".to_string(), "fcd".to_string()],
        vec!["be".to_string(), "dface".to_string(), "eabf".to_string(), "cbeda".to_string()],
        vec!["dgbef".to_string(), "gfdeba".to_string(), "afgdeb".to_string(), "gdefb".to_string()],
        vec!["bc".to_string(), "fdgcae".to_string(), "ecadgf".to_string(), "bdcega".to_string()],
        vec!["gbfde".to_string(), "fgebd".to_string(), "gedbf".to_string(), "egfa".to_string()],
        vec!["bafg".to_string(), "abgfec".to_string(), "ecfbda".to_string(), "fbag".to_string()],
        vec!["fcebg".to_string(), "dfegabc".to_string(), "dgecba".to_string(), "defacg".to_string()],
        vec!["bf".to_string(), "dfecb".to_string(), "fb".to_string(), "dgceb".to_string()],
        vec!["dgcabe".to_string(), "de".to_string(), "dgabec".to_string(), "bed".to_string()],
        vec!["acdgf".to_string(), "dbafg".to_string(), "geba".to_string(), "gbd".to_string()],
        vec!["fadbgc".to_string(), "gcfea".to_string(), "ebdg".to_string(), "gd".to_string()],
        vec!["cfa".to_string(), "gcadf".to_string(), "dagfce".to_string(), "acf".to_string()],
        vec!["acfgdb".to_string(), "gcdba".to_string(), "cegbad".to_string(), "fecdabg".to_string()],
        vec!["ebadf".to_string(), "fagde".to_string(), "cdgf".to_string(), "baedf".to_string()],
        vec!["bagce".to_string(), "bfged".to_string(), "cbfged".to_string(), "gedab".to_string()],
        vec!["cbd".to_string(), "dbcgfe".to_string(), "abdcg".to_string(), "cdaeg".to_string()],
        vec!["dfabce".to_string(), "bdaefc".to_string(), "dbfca".to_string(), "dgceab".to_string()],
        vec!["gedc".to_string(), "gbe".to_string(), "bcgea".to_string(), "gadcbf".to_string()],
        vec!["gabdcf".to_string(), "acb".to_string(), "ab".to_string(), "ab".to_string()],
        vec!["dbaefc".to_string(), "agdefc".to_string(), "ecgdbaf".to_string(), "fecdga".to_string()],
        vec!["gab".to_string(), "ag".to_string(), "dgfbe".to_string(), "ecdgab".to_string()],
        vec!["dgcfba".to_string(), "gfb".to_string(), "eadfbg".to_string(), "fcedag".to_string()],
        vec!["fedcga".to_string(), "eagcfd".to_string(), "gcfda".to_string(), "gfdea".to_string()],
        vec!["edbcg".to_string(), "becdg".to_string(), "ab".to_string(), "edbga".to_string()],
        vec!["adcbegf".to_string(), "fcea".to_string(), "acedgbf".to_string(), "dcgebf".to_string()],
        vec!["dcabfg".to_string(), "efc".to_string(), "ec".to_string(), "fgdecab".to_string()],
        vec!["bagdecf".to_string(), "df".to_string(), "fed".to_string(), "dcbf".to_string()],
        vec!["acgfd".to_string(), "bfaegc".to_string(), "gdafc".to_string(), "feagcb".to_string()],
        vec!["gbcfea".to_string(), "beadg".to_string(), "dfe".to_string(), "cdfbae".to_string()],
        vec!["bcfdag".to_string(), "fcdaeb".to_string(), "fcdab".to_string(), "ed".to_string()],
        vec!["dgcefa".to_string(), "dabce".to_string(), "gceba".to_string(), "bgefac".to_string()],
        vec!["af".to_string(), "gebdfc".to_string(), "bgdfc".to_string(), "fa".to_string()],
        vec!["gcdabe".to_string(), "cgaefdb".to_string(), "gd".to_string(), "gdfcaeb".to_string()],
        vec!["adcgef".to_string(), "fadcgbe".to_string(), "gf".to_string(), "edbfag".to_string()],
        vec!["cfegda".to_string(), "ad".to_string(), "da".to_string(), "abcgde".to_string()],
        vec!["ba".to_string(), "ebac".to_string(), "aebc".to_string(), "fabcg".to_string()],
        vec!["aebcf".to_string(), "fed".to_string(), "abedcf".to_string(), "aedfcb".to_string()],
        vec!["dgbca".to_string(), "begca".to_string(), "cbgaef".to_string(), "gceba".to_string()],
        vec!["dbafe".to_string(), "gacf".to_string(), "gdacb".to_string(), "fadgb".to_string()],
        vec!["gafde".to_string(), "bgdeaf".to_string(), "dc".to_string(), "defga".to_string()],
        vec!["gd".to_string(), "cfedb".to_string(), "defcg".to_string(), "cfadegb".to_string()],
        vec!["gfec".to_string(), "ebgdac".to_string(), "eabdf".to_string(), "gcef".to_string()],
        vec!["adfebg".to_string(), "ebcda".to_string(), "fdega".to_string(), "agfc".to_string()],
        vec!["ebgac".to_string(), "cagde".to_string(), "dc".to_string(), "faedgb".to_string()],
        vec!["dagbc".to_string(), "daegb".to_string(), "edbga".to_string(), "cag".to_string()],
        vec!["dfbagc".to_string(), "dfcge".to_string(), "gf".to_string(), "dfeac".to_string()],
        vec!["debcga".to_string(), "bgaedc".to_string(), "fdabcg".to_string(), "abgce".to_string()],
        vec!["fbcg".to_string(), "ecafd".to_string(), "cdbfe".to_string(), "cgbf".to_string()],
        vec!["fa".to_string(), "cabdge".to_string(), "acgbfe".to_string(), "cdbega".to_string()],
        vec!["dbafcg".to_string(), "befdag".to_string(), "ecfdagb".to_string(), "aebdfg".to_string()],
        vec!["cdgf".to_string(), "gd".to_string(), "dfbga".to_string(), "bdafe".to_string()],
        vec!["agbdfe".to_string(), "be".to_string(), "ecab".to_string(), "ecbgd".to_string()],
        vec!["gabfc".to_string(), "eg".to_string(), "ceg".to_string(), "cdbef".to_string()],
        vec!["cdbaef".to_string(), "decba".to_string(), "bdcaf".to_string(), "dbcae".to_string()],
        vec!["cdfba".to_string(), "bcdge".to_string(), "ae".to_string(), "cabgde".to_string()],
        vec!["gbafec".to_string(), "egdafc".to_string(), "aced".to_string(), "acbefg".to_string()],
        vec!["fac".to_string(), "abgcf".to_string(), "afbcdge".to_string(), "fgdbc".to_string()],
        vec!["dace".to_string(), "ecda".to_string(), "aced".to_string(), "ebgdf".to_string()],
        vec!["cfdea".to_string(), "cd".to_string(), "eacfg".to_string(), "aecgfbd".to_string()],
        vec!["bfcd".to_string(), "dc".to_string(), "cbfd".to_string(), "dc".to_string()],
        vec!["dgbe".to_string(), "afgdce".to_string(), "egabcd".to_string(), "gedb".to_string()],
        vec!["adfgcb".to_string(), "cbead".to_string(), "efbcad".to_string(), "dcagbe".to_string()],
        vec!["bgdacf".to_string(), "dgeabf".to_string(), "ca".to_string(), "cgbfe".to_string()],
        vec!["ea".to_string(), "gedcb".to_string(), "ea".to_string(), "acgde".to_string()],
        vec!["fabgde".to_string(), "fgac".to_string(), "acb".to_string(), "fcag".to_string()],
        vec!["dgfeb".to_string(), "cadgbf".to_string(), "egcf".to_string(), "dcfbge".to_string()],
        vec!["fb".to_string(), "gabfe".to_string(), "cbfg".to_string(), "bgafe".to_string()],
        vec!["afc".to_string(), "adgfec".to_string(), "bfgea".to_string(), "bgeacf".to_string()],
        vec!["dfabge".to_string(), "bf".to_string(), "dbaf".to_string(), "bcfaeg".to_string()],
        vec!["dbgef".to_string(), "fagce".to_string(), "edafcg".to_string(), "bdgfcae".to_string()],
        vec!["dfgbea".to_string(), "cda".to_string(), "dca".to_string(), "adc".to_string()],
        vec!["egfd".to_string(), "fedg".to_string(), "fdgeabc".to_string(), "eafdb".to_string()],
        vec!["fegdac".to_string(), "gedab".to_string(), "dgaec".to_string(), "bfdeca".to_string()],
        vec!["cae".to_string(), "fgdabc".to_string(), "decgafb".to_string(), "cfagdb".to_string()],
        vec!["abcgfe".to_string(), "bceadgf".to_string(), "feacg".to_string(), "egbf".to_string()],
        vec!["gecd".to_string(), "cgbfa".to_string(), "cafgd".to_string(), "dc".to_string()],
        vec!["acdegb".to_string(), "gabde".to_string(), "gbcae".to_string(), "abc".to_string()],
        vec!["ebcfgad".to_string(), "dfgceb".to_string(), "gdaefb".to_string(), "bfca".to_string()],
        vec!["gabed".to_string(), "gaecbd".to_string(), "ab".to_string(), "eagfcd".to_string()],
        vec!["gdb".to_string(), "dfgca".to_string(), "gfabcd".to_string(), "dacgb".to_string()],
        vec!["dceg".to_string(), "bedcfa".to_string(), "edgacb".to_string(), "dc".to_string()],
        vec!["bdacfge".to_string(), "fecgbda".to_string(), "gbcafe".to_string(), "fedcg".to_string()],
        vec!["gfdca".to_string(), "bdcfg".to_string(), "dbf".to_string(), "afgced".to_string()],
        vec!["agfcdeb".to_string(), "fagdce".to_string(), "afgbe".to_string(), "dfecga".to_string()],
        vec!["daegcf".to_string(), "faegb".to_string(), "bd".to_string(), "dba".to_string()],
        vec!["fcdaeb".to_string(), "ag".to_string(), "cegabfd".to_string(), "ga".to_string()],
        vec!["efbagcd".to_string(), "afged".to_string(), "fedgba".to_string(), "efcga".to_string()],
        vec!["afedg".to_string(), "bf".to_string(), "dfegb".to_string(), "fbgecad".to_string()],
        vec!["eagfbc".to_string(), "adecf".to_string(), "egdc".to_string(), "afdge".to_string()],
        vec!["dbgef".to_string(), "dgfbe".to_string(), "bg".to_string(), "efbgd".to_string()],
        vec!["fadceb".to_string(), "ebfdga".to_string(), "ebcad".to_string(), "bac".to_string()],
        vec!["ebdfca".to_string(), "cfagb".to_string(), "degacb".to_string(), "abdfc".to_string()],
        vec!["abf".to_string(), "cedba".to_string(), "fba".to_string(), "dgefcab".to_string()],
        vec!["cgabf".to_string(), "egaf".to_string(), "ge".to_string(), "fage".to_string()],
        vec!["cefdga".to_string(), "gdecfab".to_string(), "cfbgd".to_string(), "bcaegf".to_string()],
        vec!["bdcafeg".to_string(), "baecfdg".to_string(), "fecbd".to_string(), "gef".to_string()],
        vec!["gbad".to_string(), "bgdfcae".to_string(), "gfdcb".to_string(), "baf".to_string()],
        vec!["ebf".to_string(), "dbfcag".to_string(), "efb".to_string(), "feabc".to_string()],
        vec!["abgedf".to_string(), "cfde".to_string(), "efgbc".to_string(), "gfabcd".to_string()],
        vec!["afdgcb".to_string(), "cbga".to_string(), "dgafce".to_string(), "adegcfb".to_string()],
        vec!["cg".to_string(), "dgfc".to_string(), "cbeda".to_string(), "dfgeb".to_string()],
        vec!["dfgace".to_string(), "becafg".to_string(), "cagebf".to_string(), "fcdebag".to_string()],
        vec!["bcaed".to_string(), "edacb".to_string(), "cdaeb".to_string(), "ed".to_string()],
        vec!["badgc".to_string(), "ebfcgda".to_string(), "bdcfgae".to_string(), "abcgd".to_string()],
        vec!["fdegba".to_string(), "egadbf".to_string(), "ca".to_string(), "bfca".to_string()],
        vec!["dfecb".to_string(), "gbcdef".to_string(), "eb".to_string(), "fgceab".to_string()],
        vec!["cga".to_string(), "gac".to_string(), "dabcfeg".to_string(), "fbdgcea".to_string()],
        vec!["fgacdb".to_string(), "faedg".to_string(), "ecbdafg".to_string(), "fcedg".to_string()],
        vec!["cdagb".to_string(), "df".to_string(), "fcaebg".to_string(), "dfce".to_string()],
        vec!["bdfega".to_string(), "dgfeab".to_string(), "fdgba".to_string(), "agbdc".to_string()],
        vec!["bc".to_string(), "cgb".to_string(), "bc".to_string(), "cbg".to_string()],
        vec!["eacgf".to_string(), "agecbd".to_string(), "gd".to_string(), "gcabed".to_string()],
        vec!["adebcf".to_string(), "dcgfbea".to_string(), "deabf".to_string(), "abgec".to_string()],
        vec!["edagc".to_string(), "cebd".to_string(), "aefbg".to_string(), "bdce".to_string()],
        vec!["ed".to_string(), "gcbdefa".to_string(), "cgabdef".to_string(), "baecgf".to_string()],
        vec!["edac".to_string(), "ce".to_string(), "bagcd".to_string(), "gfeba".to_string()],
        vec!["fadcegb".to_string(), "egd".to_string(), "caedgbf".to_string(), "febdc".to_string()],
        vec!["ge".to_string(), "adcegb".to_string(), "fceagb".to_string(), "ecfba".to_string()],
        vec!["egdacb".to_string(), "eag".to_string(), "dbcage".to_string(), "ecgadbf".to_string()],
        vec!["dgfbca".to_string(), "abcdf".to_string(), "ac".to_string(), "cfgbda".to_string()],
        vec!["ebdcgaf".to_string(), "cebg".to_string(), "faegb".to_string(), "fgbae".to_string()],
        vec!["gfeba".to_string(), "ca".to_string(), "fedgca".to_string(), "gcabe".to_string()],
        vec!["debagcf".to_string(), "bfgca".to_string(), "agce".to_string(), "bgeaf".to_string()],
        vec!["gdbcfe".to_string(), "cafdbge".to_string(), "gaecbf".to_string(), "dgf".to_string()],
        vec!["dgecb".to_string(), "dacbe".to_string(), "edagfb".to_string(), "gfdbea".to_string()],
        vec!["db".to_string(), "eacdgb".to_string(), "aedbfcg".to_string(), "fcgbdea".to_string()],
        vec!["bdfega".to_string(), "afgdecb".to_string(), "fgdcba".to_string(), "gedafb".to_string()],
        vec!["gedfca".to_string(), "fabcdg".to_string(), "adfcge".to_string(), "cfe".to_string()],
        vec!["ecfgdba".to_string(), "ade".to_string(), "fcagebd".to_string(), "dea".to_string()],
        vec!["bcagef".to_string(), "afgcb".to_string(), "fcgabd".to_string(), "gcdabf".to_string()],
        vec!["ebcafg".to_string(), "fbace".to_string(), "cag".to_string(), "eacfdbg".to_string()],
        vec!["gfbad".to_string(), "aeb".to_string(), "fdabg".to_string(), "cedfbg".to_string()],
        vec!["dgef".to_string(), "fegabd".to_string(), "afebd".to_string(), "dg".to_string()],
        vec!["gcadbe".to_string(), "dcb".to_string(), "abcedg".to_string(), "edbgc".to_string()],
        vec!["fcdaeg".to_string(), "dbegacf".to_string(), "dbcf".to_string(), "cf".to_string()],
        vec!["gecaf".to_string(), "df".to_string(), "gfbdeca".to_string(), "df".to_string()],
        vec!["gfedba".to_string(), "fc".to_string(), "efdc".to_string(), "dfbaecg".to_string()],
        vec!["cfgaebd".to_string(), "aecbg".to_string(), "ecgab".to_string(), "dgbeca".to_string()],
        vec!["bgfadc".to_string(), "baedcg".to_string(), "gfc".to_string(), "gebacf".to_string()],
        vec!["bedcaf".to_string(), "dgeabc".to_string(), "acgfe".to_string(), "aeg".to_string()],
        vec!["fcgaed".to_string(), "dgfcae".to_string(), "acegb".to_string(), "ebgd".to_string()],
        vec!["fdce".to_string(), "ed".to_string(), "de".to_string(), "gedabf".to_string()],
        vec!["fgeadc".to_string(), "bg".to_string(), "gbd".to_string(), "beadg".to_string()],
        vec!["dfbagec".to_string(), "eacgfbd".to_string(), "cgedba".to_string(), "ad".to_string()],
        vec!["abe".to_string(), "fdebg".to_string(), "abe".to_string(), "dgafec".to_string()],
        vec!["dab".to_string(), "cbdafge".to_string(), "dfaec".to_string(), "dagefb".to_string()],
        vec!["bfdgec".to_string(), "be".to_string(), "be".to_string(), "fcgea".to_string()],
        vec!["bdcfa".to_string(), "efgca".to_string(), "cgd".to_string(), "aedgcb".to_string()],
        vec!["daf".to_string(), "dfcae".to_string(), "fd".to_string(), "egdabc".to_string()],
        vec!["agefbdc".to_string(), "gdfacb".to_string(), "cg".to_string(), "cafdbg".to_string()],
        vec!["fdebga".to_string(), "fgbcd".to_string(), "baefgc".to_string(), "geac".to_string()],
        vec!["gadbc".to_string(), "ebcag".to_string(), "ecgbf".to_string(), "gabefc".to_string()],
        vec!["egdacb".to_string(), "agfdeb".to_string(), "cbafg".to_string(), "gda".to_string()],
        vec!["abdfgce".to_string(), "befc".to_string(), "edc".to_string(), "debgca".to_string()],
        vec!["dcafeg".to_string(), "ce".to_string(), "fdbaecg".to_string(), "gaefb".to_string()],
        vec!["gbafcd".to_string(), "abcgf".to_string(), "agbcdf".to_string(), "ce".to_string()],
        vec!["dacf".to_string(), "bcfega".to_string(), "cafbe".to_string(), "dc".to_string()],
        vec!["daefgbc".to_string(), "edfa".to_string(), "abegd".to_string(), "bfadcg".to_string()],
        vec!["cdgea".to_string(), "aed".to_string(), "afbcgd".to_string(), "aed".to_string()],
        vec!["gfaebc".to_string(), "dagcb".to_string(), "febcg".to_string(), "ecgfdab".to_string()],
        vec!["decfb".to_string(), "gfd".to_string(), "fbcgd".to_string(), "fdg".to_string()],
        vec!["adb".to_string(), "bfadg".to_string(), "cbfead".to_string(), "ab".to_string()],
        vec!["agcf".to_string(), "ga".to_string(), "daegcfb".to_string(), "cedbg".to_string()],
        vec!["gface".to_string(), "bcaef".to_string(), "fab".to_string(), "fcabe".to_string()],
        vec!["dgecfa".to_string(), "ebdgac".to_string(), "fa".to_string(), "bdfeg".to_string()],
        vec!["fcadge".to_string(), "gdbef".to_string(), "fegbac".to_string(), "agbef".to_string()],
        vec!["cabgdf".to_string(), "ceafb".to_string(), "afgdec".to_string(), "de".to_string()],
        vec!["fb".to_string(), "baf".to_string(), "edgafb".to_string(), "cbgda".to_string()]
    ]
}
